### Find All
GET http://localhost:3000/api/users

### Find by Id
GET http://localhost:3000/api/users/1

### Find by Email
POST http://localhost:3000/api/users/email
Content-Type: application/json

{
    "email" : "admin@qpc.com"
}

### Insert
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "test.2",
    "firstname": "TestFname",
    "lastname": "TestLname",
    "email": "test.2@hotmail.com",
    "phone": "0123456789",
    "password": "password",
    "role": 4
}