GET http://localhost:3000/api/users
Content-Type: application/json

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "qcp1",
    "firstname": "test1",
    "lastname": "test1",
    "email": "test@gmail.com",
    "password": "pasokfjeuue"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "Bob@gmail.com",
    "password": "bob"
}

###
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJCb2JMZUJyaWNvbGV1ciIsImVtYWlsIjoiQm9iQGdtYWlsLmNvbSIsImlhdCI6MTY1Mjk2Njk5MywiZXhwIjoxNjUyOTY3MDEzfQ.uQUAQhqOn0h_IC7xoyV3a0jxq7dAbg-wtchdyUrOxO4
Content-Type: application/json

###
GET http://localhost:3000/api/auth/refresh_token

###
DELETE http://localhost:3000/api/auth/refresh_token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJCb2JMZUJyaWNvbGV1ciIsImVtYWlsIjoiQm9iQGdtYWlsLmNvbSIsImlhdCI6MTY1Mjk2NjIyMCwiZXhwIjoxNjUyOTY2MjQwfQ.E4wV6M9SYKmrZaINTzqmt3nnqY4wkwUmaObbnu065eg
Content-Type: application/json